django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('library/', include('library.urls', namespace='library')),
]

library/urls.py
from django.urls import path, include
from django.contrib import admin, auth
from library import views
import sys
import os

# Get the parent directory
parent_dir = os.path.dirname(os.path.realpath(__file__))

# Add the parent directory to sys.path
sys.path.append(parent_dir)

# Import the module from the parent directory
import authentication.views

app_name = 'library'

urlpatterns = [
	path("login/", authentication.views.login_page, name='login'),
	path('logout/', authentication.views.logout_page, name='logout'),
	path('admin/list/', views.BookList.as_view(), name='list'),
	path('admin/create/', views.BookCreate.as_view(), name='create'),
	path('admin/<pk>/details/', views.BookDetailsView.as_view(), name='details'),
	path('admin/<pk>/update/', views.BookUpdateView.as_view(), name='update'),
	path('list/', views.BookListUser.as_view(), name='book_user_list'),
	path('borrow/<pk>', views.borrow_return_book, name='borrow'),
	path('borrowed_books', views.BorrowedBooks.as_view(), name='borrowed_books')
]

library/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

class Book(models.Model):
    isbn = models.CharField(unique=True, max_length=13)
    title = models.CharField(max_length=150)
    author = models.CharField(max_length=100)
    year = models.PositiveBigIntegerField()
    distributor = models.CharField(max_length=150)
    genre = models.CharField(max_length=50)
    defaultBorrowDays = models.PositiveBigIntegerField()

class Issue(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    issueDate = models.DateField(null=False)
    returnDate = models.DateField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.issueDate = timezone.now()
            print('issue date', self.issueDate)
        elif self.id and not self.returnDate:
            self.returnDate = timezone.now()
            print('return Date', self.returnDate)
        return super(Issue, self).save(*args, **kwargs)

library/authentication/forms.py
# authentication/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=63)
    password = forms.CharField(max_length=63, widget=forms.PasswordInput)

library/authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy


from . import forms

def logout_page(request):
    logout(request)
    #return redirect(reverse_lazy('library:login'))
    return redirect('/library/login')


def login_page(request):
    message = ''
    form = forms.LoginForm()
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
            )
            if user:
                login(request, user)
                message = f'Hello {user.username}! You have been logged in'
                return redirect('/library/list/')
            else:
                return redirect('/library/login')
                message = 'Login failed!'
    return render(request, 'authentication/login.html', context={'form': form})
            

library/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from .models import Book, Issue
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required

# Create your views here.

from django.http import HttpResponse


class BookList(ListView):
    model = Book


class BookListUser(LoginRequiredMixin, ListView):
    login_url = "/library/login"
    redirect_field_name = ""

    def get_template_names(self) -> list[str]:
        return ["library/book_user_list.html"]

    model = Book

    def get_context_data(self, **kwargs):
        context = super(BookListUser, self).get_context_data(**kwargs)
        book_status = {}
        issue_list = Issue.objects.filter(returnDate=None)
        user = self.request.user.get_username()

        for issue in issue_list:
            name = issue.user.get_username()
            if name == user:
                book_status[issue.book.id] = ['Return', name]
            else:
                book_status[issue.book.id] = ['Unavailable', name]
        context['book_status'] = book_status
        return context


class BorrowedBooks(BookListUser):
    def get_queryset(self, *args, **kwargs):
        user = User.objects.get(pk=self.request.user.pk)
        if user.is_superuser:
            all_issues = Issue.objects.filter(returnDate=None)
            return super().get_queryset().filter(issue__in=all_issues).order_by('issue__user__username')
        else:
            user_issues = Issue.objects.filter(user=user, returnDate=None)
            return super().get_queryset().filter(issue__in=user_issues)


class BookDetailsView(DetailView):
    model = Book


class BookUpdateView(UpdateView):
    model = Book

    fields = [
        "isbn",
        "title",
        "author",
        "year",
        "distributor",
        "genre",
        "defaultBorrowDays"
    ]

    success_url = "/library/admin/list"


class BookCreate(PermissionRequiredMixin, CreateView):
    login_url = "/library/login"
    redirect_field_name = ""
    permission_required = "library.book.add_book"
    model = Book
    fields = [
        "isbn",
        "title",
        "author",
        "year",
        "distributor",
        "genre",
        "defaultBorrowDays"
    ]

    success_url = "/library/admin/list"


@permission_required(perm=['library.add_issue', 'library.change_issue', 'library.view_issue',
                           'library.view_book'], raise_exception=True)
def borrow_return_book(request, pk):
    # Issue.objects.create(user=User.objects.get(pk=request.user.pk), book=Book.objects.get(pk=pk))
    # issue_obj = Issue(user=User.objects.get(pk=request.user.pk), book=Book.objects.get(pk=pk))
    # issue_obj.save()
    # print(request, pk)
    # print(request.user)
    # return redirect("/library/list")

    user = User.objects.get(pk=request.user.pk)
    book = Book.objects.get(pk=pk)

    issues = Issue.objects.filter(user=user, book=book)

    for issue in issues:
        if issue.issueDate and issue.returnDate is None:
            issue.save()
            break
    else:
        issue = Issue(user=user, book=book)
        issue.save()

    return redirect("/library/list")

library/templates/authentication/base.html
<!-- templates/base.html--> 
<!-- templates/registration/login.html -->

<html>
    <head>
        <title>FotoBlog</title>
    </head>
    <body>
        <h1>FotoBlog</h1>
        {% block content %}{% endblock content %}
        # templates/base.html
            <html>
                <head>
                    <title>FotoBlog</title>
                </head>
                <body>
                    <h1>FotoBlog</h1>
                    {% block content %}{% endblock content %}
                    {%  if user.is_authenticated %}
                        <p>You are logged in as {{ request.user }}. Click here to <a href="{% url 'library:logout' %}">Log out</a></p>
                    {% endif %}
                </body>
            </html>
    </body>
</html>

library/templates/authentication/login.html
<!-- <authentication/templates/authentication/login.html -->
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-6 offset-md-3">
        <h3>Please log in</h3>
        <form method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-outline-primary">Log In</button>
        </form>
    </div>
    
{% endblock %}

library/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Library App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container">
    <br/>
      {% block content %}

      {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

library/templates/library/book_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container heading-container">
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Author</th>
                    <th>ISBN</th>
                    <th>Distributor</th>
                    <th>Year</th>
                    <th>Genre</th>

                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ object.title }}</td>
                    <td>{{ object.author }}</td>
                    <td>{{ object.isbn }}</td>
                    <td>{{ object.distributor }}</td>
                    <td>{{ object.year }}</td>
                    <td>{{ object.genre }}</td>
                </tr>
            </tbody>
        </table>
        <a href="{% url 'library:list' %}" class="btn btn-outline-primary shadow shadow-5-strong">Back</a>
    </div>
</div>
{% endblock %}

library/templates/library/book_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content%}

<form method="POST" enctype="multipart/form-data">
 
    <!-- Security token -->
    {% csrf_token %}
 
    <!-- Using the formset -->
    {{ form|crispy }}

    <button type="submit" class="btn btn-outline-primary">Update</button>
</form>

{% endblock %}

library/templates/library/book_list.html
<!-- https://docs.djangoproject.com/en/4.2/intro/tutorial03/ -->

{% extends 'base.html' %}

{% block content %}
    <div class="container heading-container">
        <h2 align="center">Books</h2>
        <div class="table-responsive">
            <table class="table">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Author</th>
                    <th>ISBN</th>
                    <th>Details</th>
                    <th>Update</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                <tr>
                    <td>{{ object.title }}</td>
                    <td>{{ object.author }}</td>
                    <td>{{ object.isbn }}</td>
                    <td><a href="{% url 'library:details' pk=object.pk %}" class="btn btn-outline-primary">Details</a></td>
                    <td><a href="{% url 'library:update' pk=object.pk %}" class="btn btn-outline-primary">Update</a></td>

                <!-- <div class="col-md-6">
                        <div class="card-body">
                            <h5 class="card-title">{{ object.title }}</h5>
                            <p class="card-text">{{ object.author }}</p>
                        </div>
                        <div class="card-footer">
                            
                            <a href="{% url 'library:details' pk=object.pk %}" class="btn btn-secondary">Details</a>
                        </div>
                </div> -->
                    <!-- If object_list is empty  -->
                {% empty %}
                    <p>No objects yet.</p>
                {% endfor %}
                </tr>
            </tbody>
            </table>
        </div>
    </div>
{% endblock %}

library/templates/library/book_user_list.html
<!-- https://docs.djangoproject.com/en/4.2/intro/tutorial03/ -->

{% extends 'base.html' %}

{% load custom_filters %}

{% block content %}
    <div class="container heading-container">
        <h2 align="center">Books</h2>
        <div class="table-responsive">
            <table class="table">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Author</th>
                    <th>ISBN</th>
                    <th>Details</th>
                    {% if user.is_superuser %}
                        <th>Update</th>
                        <th>Borrowed by</th>
                    {% else %}
                        <th>Borrow/Return</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                <tr>
                    <td>{{ object.title }}</td>
                    <td>{{ object.author }}</td>
                    <td>{{ object.isbn }}</td>
                    <td><a href="{% url 'library:details' pk=object.pk %}" class="btn btn-outline-primary">Details</a></td>
                    {% if user.is_superuser %}
                        <td><a href="{% url 'library:update' pk=object.pk %}" class="btn btn-outline-primary">Update</a></td>
                    {% endif %}
                    {% if object.id in book_status %}
                        {% for key, value in book_status.items %}
                            {% if user.is_superuser and key == object.id %}
                                <td>{{ value.1 }}</td>
                            {% else %}
                                {% if key == object.id and value.0 == 'Return' %}
                                <td><a href="{% url 'library:borrow' pk=object.pk %}" class="btn btn-outline-warning">Return</a></td>
                                {% elif key == object.id and value.0 == 'Unavailable' %}
                                    <td><button class="btn btn-outline-secondary" disabled>Unavailable</button></td>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    {% elif not user.is_superuser %}
                            <td><a href="{% url 'library:borrow' pk=object.pk %}" class="btn btn-outline-primary">Borrow</a></td>
                    {% endif %}
                {% empty %}
                    <p>No objects yet.</p>
                {% endfor %}
                </tr>
            </tbody>
            </table>
        </div>
    </div>
{% endblock %}

library/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      {% if user.is_authenticated %}
      <a class="navbar-brand" href="{% url 'library:book_user_list' %}">Library</a>
      {% else %}
      <a class="navbar-brand" href="{% url 'library:login' %}">Library</a>
      {% endif %}
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav align-items-center">
          {%  if user.is_authenticated %}
            <li class="nav-item" style="color:crimson;">Hi {{ request.user }}!</li>
            <li class="nav-item"></li><a class="nav-link" href="{% url 'library:logout' %}">Log out</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'library:borrowed_books' %}">Borrowed books</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>